name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/workspace-app:latest
          docker build -t $IMAGE_URI .
          docker tag $IMAGE_URI $IMAGE_URI

      - name: Push image to Amazon ECR
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/workspace-app:latest
          docker push $IMAGE_URI

      - name: Update ECS service with latest image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/workspace-app:latest
          aws ecs update-service \
            --cluster ProdCluster \
            --service workspace-service \
            --force-new-deployment
